runners:
 ubuntu-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest

jobs:
  check-i2c-connection:
    runner: ubuntu-runner
    device: raspberry-pi-4
    input:
      artifact:
        - id_rsa
    steps:
      - run:
          name: Setup SSH keys
          command: |
            mkdir ~/.ssh
            cp ./id_rsa ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
      - run:
          name: Set i2c
          on-device: True
          command: |
            sudo raspi-config nonint do_i2c 0
      - run:
          name: Install i2c
          on-device: True
          command: |
            sudo apt-get install i2c-tools
      - run:
          name: Reboot
          on-device: True
          command: |
            sudo reboot
      - run:
          name: Wait for reboot
          command: sleep 5
      - run:
          name: Check i2c connection
          on-device: True
          command: |
            sudo i2cdetect -y 1
          fail: "Error"

  run-display:
    runner: ubuntu-runner
    device: raspberry-pi-4
    input:
      artifact:
        - id_rsa
    steps:
      - run:
          name: Setup SSH keys
          command: |
            mkdir ~/.ssh
            cp ./id_rsa ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
      - transfer:
          name: Transfer
          SOURCE: ./display-hello-world.py
          DESTINATION: andrewswirski@192.168.1.95:~/

workflows:
  getting-started-rasp-pi:
    jobs:
      # - check-i2c-connection
      - run-display